package com.example.nuki_sesami_app.base

const val NUKI_SESAMI_DEFAULT_DEVICE_ID = "3807B7EC"
const val NUKI_SESAMI_DEFAULT_MQTT_HOSTNAME = "192.168.178.56"
const val NUKI_SESAMI_DEFAULT_MQTT_PORT = 1883
const val NUKI_SESAMI_DEFAULT_MQTT_USERNAME = "sesami"
const val NUKI_SESAMI_DEFAULT_MQTT_PASSWORD = ""
const val NUKI_SESAMI_DEFAULT_BLUETOOTH_ADDRESS = "B8:27:EB:B9:2A:F0"
const val NUKI_SESAMI_DEFAULT_BLUETOOTH_CHANNEL = 4

const val NUKI_SESAMI_MIN_MQTT_PORT = 1
const val NUKI_SESAMI_MAX_MQTT_PORT = 65535

const val NUKI_SESAMI_MIN_BLUETOOTH_CHANNEL = 1
const val NUKI_SESAMI_MAX_BLUETOOTH_CHANNEL = 9
